window.DASHBOARD_ITEMS = [
  {
    id: "mfds-driving-warning",
    title: "졸음 유발 약 복용 후 운전 주의 이슈 재부각",
    source: "식약처",
    publishedAt: "2026-04-21 09:00",
    category: "official",
    tags: ["식약처", "운전주의", "감기약", "쇼츠유망"],
    summary: "졸음을 유발할 수 있는 성분과 복약 후 운전 위험에 대한 주의 메시지를 다시 확인할 필요가 있는 흐름.",
    whyItMatters: "운전, 기계 조작, 고령자 낙상 같은 실제 사고와 바로 연결된다.",
    shortsScore: 9,
    shortsTitle: "졸리는 약 먹고 운전하면 진짜 위험한 이유",
    cautionNote: "성분과 개인 상태에 따라 다를 수 있어 복약 안내문 확인 필요",
    originalUrl: "https://www.mfds.go.kr/",
    picked: true,
    priority: 98
  },
  {
    id: "dailypharm-donepezil-trend",
    title: "도네페질+메만틴 경쟁 심화, 치매약 시장 움직임 포착",
    source: "데일리팜",
    publishedAt: "2026-04-21 08:20",
    category: "industry",
    tags: ["치매약", "업계", "쇼츠유망"],
    summary: "치매 복합제 시장 경쟁이 커지면서 관련 처방과 관심이 높아질 수 있는 흐름.",
    whyItMatters: "치매약은 보호자 관심이 매우 높아서 콘텐츠 반응이 크다.",
    shortsScore: 8,
    shortsTitle: "치매약, 같이 먹는 약 조합이 왜 중요할까?",
    cautionNote: "약 변경은 반드시 진료 후 결정해야 함",
    originalUrl: "https://www.dailypharm.com/",
    picked: true,
    priority: 90
  },
  {
    id: "kormedi-antihistamine",
    title: "알레르기 시즌, 항히스타민제 졸림 부작용 다시 관심",
    source: "코메디닷컴",
    publishedAt: "2026-04-21 07:40",
    category: "public",
    tags: ["항히스타민제", "운전주의", "계절이슈", "쇼츠유망"],
    summary: "봄철 알레르기약 복용이 늘며 졸림, 집중력 저하, 운전 주의가 함께 언급되는 추세.",
    whyItMatters: "대중 관심과 계절성이 동시에 있어서 조회수형 소재가 되기 쉽다.",
    shortsScore: 9,
    shortsTitle: "알레르기약 먹고 졸린 이유, 그냥 넘기면 안 됩니다",
    cautionNote: "약마다 졸림 정도 차이가 큼",
    originalUrl: "https://kormedi.com/",
    picked: true,
    priority: 95
  },
  {
    id: "hidoc-painkiller-bloodpressure",
    title: "진통제를 자주 먹는 사람, 혈압약과 함께 복용 시 주의",
    source: "하이닥",
    publishedAt: "2026-04-20 18:10",
    category: "public",
    tags: ["진통제", "고혈압", "병용금기", "쇼츠유망"],
    summary: "일부 소염진통제는 혈압 조절에 영향을 줄 수 있어 만성질환자에게 주의가 필요하다는 흐름.",
    whyItMatters: "고혈압약, 관절약은 중장년층 관심도가 매우 높다.",
    shortsScore: 10,
    shortsTitle: "혈압약 드시는 분, 진통제 아무거나 드시면 안 됩니다",
    cautionNote: "복용 중인 약 성분 확인 필요",
    originalUrl: "https://www.hidoc.co.kr/",
    picked: true,
    priority: 99
  },
  {
    id: "kpanews-pharmacy-supply",
    title: "약국 소모품 수급 이슈, 현장 체감과 실제 복약 동선 변화 가능성",
    source: "약사공론",
    publishedAt: "2026-04-21 10:00",
    category: "industry",
    tags: ["약국", "업계", "대중관심"],
    summary: "시럽병, 약포지 같은 조제 소모품 수급 이슈가 약국 현장에 영향을 주는 흐름.",
    whyItMatters: "직접적인 약효 정보는 아니지만 약국 이용 경험과 연결될 수 있다.",
    shortsScore: 6,
    shortsTitle: "약국에서 약 받는 방식, 왜 달라질 수 있을까?",
    cautionNote: "지역과 약국마다 상황 차이 있음",
    originalUrl: "https://www.kpanews.co.kr/",
    picked: true,
    priority: 72
  },
  {
    id: "healthchosun-coldmed-bp",
    title: "감기약 성분 때문에 혈압이 오를 수 있다는 경고성 정보 주목",
    source: "헬스조선",
    publishedAt: "2026-04-20 15:30",
    category: "public",
    tags: ["감기약", "고혈압", "대중관심", "쇼츠유망"],
    summary: "고혈압 환자가 감기약을 고를 때 특정 성분을 주의해야 한다는 주제가 반복적으로 관심을 끈다.",
    whyItMatters: "시니어뿐 아니라 가족들도 같이 궁금해하는 실전형 정보다.",
    shortsScore: 9,
    shortsTitle: "고혈압 있으시면 감기약 이 성분은 조심하세요",
    cautionNote: "모든 감기약이 같은 것은 아니며 성분 확인 필요",
    originalUrl: "https://www.healthchosun.com/",
    picked: true,
    priority: 94
  },
  {
    id: "mfds-recall-sample",
    title: "회수·판매중지 공지 체크 필요 품목 발생 시 우선 노출",
    source: "식약처",
    publishedAt: "2026-04-20 11:00",
    category: "official",
    tags: ["식약처", "회수", "즉시확인"],
    summary: "회수나 판매중지 정보는 발견 즉시 최상단에 올리는 운영 규칙용 샘플 카드.",
    whyItMatters: "실제 건강과 안전에 직접 영향을 준다.",
    shortsScore: 8,
    shortsTitle: "지금 바로 확인해야 할 회수 의약품 정보",
    cautionNote: "제품명, 제조번호, 회수 사유를 원문에서 반드시 재확인",
    originalUrl: "https://www.mfds.go.kr/",
    picked: false,
    priority: 100
  }
];
